### ISSUE TITLE
Neat build - any updates on battery life?

### ISSUE THREAD

**Issue by peterhoeg** [kimmobrunfeldt/eink-weather-display#1]
Have you had it running long enough to be able to say anything about expected battery life other than the calculation you mention in the README based on theoretical use?

**Comment by kimmobrunfeldt** [comment]
Update so far:

* Sunday evening: 100%
* Monday morning: 92%
* Tuesday: 91%     <--  bumped display refresh to 5x a day
* Wednesday: 91%
* Thursday: 91%

I'll try to remember adding the the levels and voltages after a few weeks, they are logged on rendering. I recall reading from PiJuice GH issues that the battery levels are not super accurate. Looking good so far.

**Comment by peterhoeg** [comment]
Any more data points by chance? I am considering to build an ESP32 based version (I don't have any rPis but lots of ESP32).

**Comment by kimmobrunfeldt** [comment]
@peterhoeg Here's some data. Unfortunately the numbers fluctuate a bit. I had to take the device off the wall and put it to charger while doing additional tweaking. It's been on the wall roughly 5 days without being connected to charger. 

![graph](https://user-images.githubusercontent.com/1232405/204451631-2002f442-6af2-4cdc-a1c8-2e35c68b6318.png)

Linear regression of battery level based on last 5 days:

![battery-linear-regression](https://user-images.githubusercontent.com/1232405/204451640-dcca9044-f52e-452c-a708-468eb1dd4c11.png)

**Comment by peterhoeg** [comment]
Thanks. I just wanted to say thank you for the idea of pre-rendering the screens rather than having to handle that on the rpi/esp32.

**Comment by kimmobrunfeldt** [comment]
Adding more info to this issue also to document these for myself. Here's how the projected battery level looks like now:

![graph](https://user-images.githubusercontent.com/1232405/205268979-c3b6a1f8-2ad0-4d5e-a98b-70f2fd17ebc6.png)

I have a hunch that the charge level doesn't drop in a linear way though. But even if the battery didn't last that long, I've been happy with the battery life so far. A few reference issues from PiJuice repo:

* https://github.com/PiSupply/PiJuice/issues/702
* https://github.com/PiSupply/PiJuice/issues/107

**Comment by kimmobrunfeldt** [comment]
Update:

![graph](https://user-images.githubusercontent.com/1232405/210208032-c8e12f90-b435-4294-9824-198ede7cf44e.png)

**Comment by kimmobrunfeldt** [comment]
During last week the discharge rate changed. I've been expecting something like this. Still the linear regression looks like it could last ~8months total, but I'm guessing the actual number is ~4-5months.
![graph](https://user-images.githubusercontent.com/1232405/212166411-691c610e-9963-4840-bcbe-997eb1596c45.png)

**Comment by peterhoeg** [comment]
Thanks for all the updates.

To me it doesn’t really matter if it’s 2 months or 8 months. Longer is of course better, but even once a month is managable.

**Comment by kimmobrunfeldt** [comment]
Today I fully recharged the battery from 8% back to 100% the first time. Battery lasted roughly 4 months, when updating the screen 6 times a day.
